services:
  web:
    image: srdiaz/flask-vehiculos:1.0
    container_name: flask_vehiculos
    ports:
      - "5000:5000"
    environment:
      - DB_PATH=/sqlite3-db/coches.db
    volumes:
      - sqlite_db:/sqlite3-db
    restart: unless-stopped

volumes:
  sqlite_db:
