name: CI/CD Deployment IAW

on: 
  push:
    branches: [ "main" ]

jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Autenticación en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Construcción y envío de la imagen
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true 
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/practica-iaw-flask:latest

      - name: Despliegue en servidor remoto
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. Bajar la última imagen de Docker Hub
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/practica-iaw-flask:latest
            # 2. Detener y borrar el contenedor actual si existe
            docker stop flask-app || true
            docker rm flask-app || true
            # 3. Arrancar el nuevo contenedor
            docker run -d --name flask-app -p 80:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/practica-iaw-flask:latest